/* Generated by tools/generate_dino_sprites.py; do not edit.
 * Sprite artwork: Copyright 2015 The Chromium Authors. All rights reserved.
 * BSD license: assets/dino/chromium/LICENSE. Source PNG SHA256:
 * 04d05978fdb111358073ab0524e5c1fafc0826615c206987618416b8bd8a4747
 * Original 1x pixels and alpha, inverted luminance for the black night field.
 */
#pragma once

typedef enum {
    DINO_SPRITE_TREX_STAND,
    DINO_SPRITE_TREX_BLINK,
    DINO_SPRITE_TREX_RUN_0,
    DINO_SPRITE_TREX_RUN_1,
    DINO_SPRITE_TREX_DUCK_0,
    DINO_SPRITE_TREX_DUCK_1,
    DINO_SPRITE_TREX_CRASH,
    DINO_SPRITE_CACTUS_SMALL,
    DINO_SPRITE_CACTUS_LARGE,
    DINO_SPRITE_BIRD_0,
    DINO_SPRITE_BIRD_1,
    DINO_SPRITE_COUNT
} dino_sprite_id_t;
