#!/usr/bin/env python3
"""Reproduce Chromium 98 classic 1x sprites as lossless AL88 night images.

The pinned upstream PNG and BSD license live in assets/dino/chromium. No AI,
resampling, alpha removal, or runtime pixel buffer is involved. AL88 stores
inverted luminance followed by the original alpha, in LVGL's native order.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "04d05978fdb111358073ab0524e5c1fafc0826615c206987618416b8bd8a4747"
# Exact LDPI atlas positions + Trex.animFrames offsets from pinned Chromium.
# Ducking has a logical height of 25 but upstream draws the whole 59x47 cell;
# keeping its transparent top padding preserves every original outline pixel.
COLLISION_FRAMES = {
    "trex_stand": (848, 2, 44, 47),
    "trex_blink": (892, 2, 44, 47),
    "trex_run_0": (936, 2, 44, 47),
    "trex_run_1": (980, 2, 44, 47),
    "trex_duck_0": (1112, 2, 59, 47),
    "trex_duck_1": (1171, 2, 59, 47),
    "trex_crash": (1068, 2, 44, 47),
    "cactus_small": (228, 2, 17, 35),
    "cactus_large": (332, 2, 25, 50),
    "bird_0": (134, 2, 46, 40),
    "bird_1": (180, 2, 46, 40),
}
DECORATION_FRAMES = {
    "horizon_0": (2, 54, 600, 12),
    "horizon_1": (602, 54, 600, 12),
    "cloud": (86, 2, 46, 14),
    "game_over": (655, 15, 191, 11),
    "restart": (2, 68, 36, 32),
    "hi": (755, 2, 20, 13),
}
DECORATION_FRAMES.update({f"digit_{n}": (655 + n * 10, 2, 10, 13) for n in range(10)})
FRAMES = COLLISION_FRAMES | DECORATION_FRAMES
NOTICE = """/* Generated by tools/generate_dino_sprites.py; do not edit.
 * Sprite artwork: Copyright 2015 The Chromium Authors. All rights reserved.
 * BSD license: assets/dino/chromium/LICENSE. Source PNG SHA256:
 * 04d05978fdb111358073ab0524e5c1fafc0826615c206987618416b8bd8a4747
 * Original 1x pixels and alpha, inverted luminance for the black night field.
 */
"""


def load_source():
    path = ROOT / "assets/dino/chromium/100-offline-sprite.png"
    if hashlib.sha256(path.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise ValueError("Upstream source PNG does not match the pinned SHA256")
    return Image.open(path).convert("RGBA")


def frame(source, name):
    x, y, width, height = FRAMES[name]
    return source.crop((x, y, x + width, y + height))


def al88(image):
    pixels = []
    for r, g, b, a in image.get_flattened_data():
        if r != g or g != b:
            raise ValueError("Selected sprite contains color; AL88 would lose information")
        pixels.extend((255 - r, a))
    return bytes(pixels)


def night_image(image):
    out = Image.new("RGBA", image.size)
    out.putdata([(255-r, 255-g, 255-b, a) for r, g, b, a in image.get_flattened_data()])
    return out


def pixel_data(image):
    try:
        return "AL88", image.width * 2, al88(image)
    except ValueError:
        # The large cactus cell includes upstream's faint pink bottom matte.
        # Preserve it exactly; forcing monochrome would alter the source pixels.
        raw = bytes(v for r, g, b, a in image.get_flattened_data()
                    for v in (255-b, 255-g, 255-r, a))
        return "ARGB8888", image.width * 4, raw


def collision_rows(image):
    # Collidable body pixels exclude the white matte/outline from the day atlas.
    # Exact per-row bits remove transparent corners without coarse rectangles.
    return [sum(1 << x for x in range(image.width)
                if (p := image.getpixel((x, y)))[3] >= 128 and p[0] < 128)
            for y in range(image.height)]


def generated_files(source):
    ids = NOTICE + "#pragma once\n\ntypedef enum {\n"
    ids += "".join(f"    DINO_SPRITE_{name.upper()},\n" for name in COLLISION_FRAMES)
    ids += "    DINO_SPRITE_COUNT\n} dino_sprite_id_t;\n"
    masks = NOTICE + '#pragma once\n#include "dino_sprite_ids.h"\n#include <stdint.h>\n\n'
    masks += "typedef struct { uint8_t width, height; const uint64_t *rows; } dino_sprite_mask_t;\n\n"
    images = NOTICE + '#pragma once\n#include "lvgl.h"\n#include "dino_sprite_ids.h"\n\n'
    images += '#if !LV_DRAW_SW_SUPPORT_AL88\n#error "Dino original sprites require LV_DRAW_SW_SUPPORT_AL88"\n#endif\n\n'
    for name in FRAMES:
        cropped = frame(source, name)
        color_format, stride, data = pixel_data(cropped)
        images += f"_Alignas(4) static const uint8_t dino_pixels_{name}[] = {{\n"
        for offset in range(0, len(data), 32):
            images += "    " + ",".join(f"0x{v:02x}" for v in data[offset:offset + 32]) + ",\n"
        images += "};\n"
        images += f"static const lv_image_dsc_t dino_image_{name} = {{\n"
        images += f"    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_{color_format}, "
        images += f".w = {cropped.width}, .h = {cropped.height}, .stride = {stride}}},\n"
        images += f"    .data_size = sizeof(dino_pixels_{name}), .data = dino_pixels_{name},\n}};\n\n"
        if name in COLLISION_FRAMES:
            masks += f"static const uint64_t dino_mask_{name}[] = {{\n"
            masks += "".join(f"    UINT64_C(0x{row:016x}),\n" for row in collision_rows(cropped))
            masks += "};\n"
    masks += "static const dino_sprite_mask_t dino_sprite_masks[DINO_SPRITE_COUNT] = {\n"
    images += "static const lv_image_dsc_t *const dino_sprite_images[DINO_SPRITE_COUNT] = {\n"
    for name, (_, _, w, h) in COLLISION_FRAMES.items():
        masks += f"    [DINO_SPRITE_{name.upper()}] = {{{w}, {h}, dino_mask_{name}}},\n"
        images += f"    [DINO_SPRITE_{name.upper()}] = &dino_image_{name},\n"
    masks += "};\n"
    images += "};\n"
    images += "static const lv_image_dsc_t *const dino_digit_images[10] = {\n"
    images += "".join(f"    &dino_image_digit_{n},\n" for n in range(10)) + "};\n"
    return {"main/dino_sprite_ids.h": ids, "main/dino_sprite_masks.h": masks,
            "main/passport_dino_sprites.h": images}


def preview(source, directory):
    directory.mkdir(parents=True, exist_ok=True)
    sheet = Image.new("RGB", (720, 338), "#111318")
    draw = ImageDraw.Draw(sheet)
    for index, name in enumerate(COLLISION_FRAMES):
        x, y = 14 + (index % 6) * 118, 14 + (index // 6) * 156
        sprite = night_image(frame(source, name))
        tile = Image.new("RGBA", (59, 50), "black")
        tile.alpha_composite(sprite, (0, 0))
        sheet.paste(tile.resize((118, 100), Image.Resampling.NEAREST).convert("RGB"), (x, y))
        draw.text((x, y + 108), name, fill="#cbd1d8")
        draw.text((x, y + 124), f"{sprite.width} x {sprite.height}, 2x", fill="#8d939e")
    sheet.save(directory / "01 Chromium 原始像素对照.png")
    field = Image.new("RGBA", (216, 142), "black")
    field.alpha_composite(night_image(frame(source, "horizon_0")), (-70, 119))
    field.alpha_composite(night_image(frame(source, "cloud")), (112, 16))
    field.alpha_composite(night_image(frame(source, "trex_run_0")), (28, 85))
    field.alpha_composite(night_image(frame(source, "cactus_large")), (151, 82))
    field.convert("RGB").save(directory / "02 Dino 实际像素预览.png")
    field.resize((432, 284), Image.Resampling.NEAREST).convert("RGB").save(directory / "03 Dino 两倍像素预览.png")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    source = load_source()
    for path, content in generated_files(source).items():
        output = ROOT / path
        if args.check:
            if not output.exists() or output.read_text() != content:
                raise SystemExit(f"Stale generated sprite: {path}")
        else:
            output.write_text(content)
    if args.preview_dir:
        preview(source, args.preview_dir)
    count = sum(len(pixel_data(frame(source, name))[2]) for name in FRAMES)
    print(f"Dino sprites: {'checked' if args.check else 'generated'}, {len(FRAMES)} frames, {count} ROM pixel bytes, no runtime decode buffer")


if __name__ == "__main__":
    main()
