#!/usr/bin/env python3
"""Compile unchanged source artwork directly to native display RGB565 pixels.

No redraw, retouching, sharpening or new image generation: this is the same
technical color/alpha conversion used by the device preview, at display size.
"""
import argparse
from pathlib import Path
import struct

from passport_bridge import load_avatar_source, rgb565_canvas, rgb565_image

ROOT = Path(__file__).resolve().parents[1]
SIZE = 160


def generate(preview_directory=None, check=False):
    parts = ['#include "passport_assets.h"\n', '// Generated by tools/generate_builtin_avatars.py; source artwork unchanged.\n']
    for stage, key in enumerate(("winter", "mage", "red")):
        source = ROOT / "assets/images" / f"aoko-{key}.png"
        raw = rgb565_canvas(load_avatar_source(source), SIZE)
        values = struct.unpack(f"<{SIZE * SIZE}H", raw)
        parts.append(f"const uint16_t passport_avatar_{key}[PASSPORT_BUILTIN_AVATAR_SIZE * PASSPORT_BUILTIN_AVATAR_SIZE] = {{\n")
        parts.extend("    " + ",".join(f"0x{x:04x}" for x in values[i:i+24]) + ",\n" for i in range(0, len(values), 24))
        parts.append("};\n")
        if preview_directory is not None and not check:
            preview_directory.mkdir(parents=True, exist_ok=True)
            rgb565_image(raw, SIZE).save(preview_directory / f"stage-{stage}.png")
    destination = ROOT / "main/passport_avatar_data.c"
    generated = "".join(parts)
    if check:
        if destination.read_text() != generated:
            raise SystemExit("Built-in display assets are stale")
    else:
        destination.write_text(generated)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview-directory", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generate(args.preview_directory, args.check)
