#!/usr/bin/env python3
"""Generate the firmware constants from the same layout JSON used by the Mac app."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "badge-layout.json"
HEADER = ROOT / "main" / "passport_layout.h"
ELEMENTS = {"time", "battery", "avatar", "name", "title", "intro", "token_caption", "token_value", "separator"}
FONTS = {"lv_font_montserrat_14": (14, 16, 3), "passport_font_14": (14, 18, 4), "passport_font_20": (20, 25, 6)}


def integer(value, name, minimum=0):
    if type(value) is not int or value < minimum:
        raise ValueError(name + " must be an integer >= " + str(minimum))
    return value


def validate(layout):
    if layout.get("version") != 1 or layout.get("width") != 240 or layout.get("height") != 320:
        raise ValueError("layout v1 requires the verified 240x320 device")
    colors = layout.get("colors", {})
    for name in ("background", "primary", "secondary", "dim", "accent", "panel", "separator", "selection", "warning"):
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", colors.get(name, "")):
            raise ValueError("invalid or missing color: " + name)
    if set(layout.get("elements", {})) != ELEMENTS:
        raise ValueError("layout must contain the exact v1 element set")
    for name, box in layout["elements"].items():
        for key in ("x", "y", "width", "height"):
            integer(box.get(key), name + "." + key, 1 if key in ("width", "height") else 0)
        if box["x"] + box["width"] > layout["width"] or box["y"] + box["height"] > layout["height"]:
            raise ValueError(name + " extends beyond the display")
        if name == "avatar":
            for key in ("source_width", "source_height"):
                integer(box.get(key), name + "." + key, 1)
            if box["width"] * box["source_height"] != box["height"] * box["source_width"]:
                raise ValueError("avatar scaling must preserve its source aspect ratio")
            if box["width"] * 256 % box["source_width"]:
                raise ValueError("avatar scale must be exactly representable in LVGL units")
            if box.get("pivot_x") != 0 or box.get("pivot_y") != 0:
                raise ValueError("avatar uses a top-left pivot for shared coordinates")
        else:
            if box.get("color") not in colors:
                raise ValueError("invalid color reference for " + name)
            if name != "separator":
                if box.get("c_font") not in FONTS or FONTS[box["c_font"]] != (box.get("font_size"), box.get("line_height"), box.get("baseline_from_bottom")):
                    raise ValueError("font size or actual LVGL line metrics mismatch: " + name)
                if box.get("align") not in ("left", "center", "right"):
                    raise ValueError("invalid alignment for " + name)
                if box.get("overflow", "clip") not in ("clip", "ellipsis"):
                    raise ValueError("invalid overflow mode for " + name)
                if type(box.get("letter_spacing")) is not int or not -4 <= box["letter_spacing"] <= 8:
                    raise ValueError("invalid letter spacing for " + name)
                if box.get("kerning") != (box["c_font"] == "lv_font_montserrat_14"):
                    raise ValueError("kerning must match the generated font: " + name)
                integer(box.get("max_lines"), name + ".max_lines", 1)
                if box["height"] < box["max_lines"] * box["line_height"]:
                    raise ValueError("insufficient line height for " + name)
    labels = layout.get("labels", {})
    if set(labels) != {"token_caption", "token_caption_stale", "time_unknown", "battery_unknown", "tokens_unknown"}:
        raise ValueError("layout must contain the exact v1 label set")
    for label in labels.values():
        if not isinstance(label, str) or any(ord(ch) < 32 for ch in label):
            raise ValueError("layout labels must be printable text")
    return layout


def load_layout(path=SOURCE):
    return validate(json.loads(Path(path).read_text(encoding="utf-8")))


def render_header(layout):
    validate(layout)
    canonical = json.dumps(layout, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    digest = hashlib.sha256(canonical).hexdigest()
    lines = ["/* Generated by tools/generate_badge_layout.py; edit assets/badge-layout.json. */",
             "#pragma once", "#include <stdint.h>", "",
             '#define PASSPORT_LAYOUT_SHA256 "' + digest + '"',
             "#define PASSPORT_LAYOUT_VERSION 1", "#define PASSPORT_LAYOUT_WIDTH 240", "#define PASSPORT_LAYOUT_HEIGHT 320", ""]
    for name, value in sorted(layout["colors"].items()):
        lines.append("#define PASSPORT_LAYOUT_COLOR_" + name.upper() + " UINT32_C(0x" + value[1:].upper() + ")")
    lines.append("")
    for name, text in sorted(layout["labels"].items()):
        lines.append("#define PASSPORT_LAYOUT_TEXT_" + name.upper() + " " + json.dumps(text, ensure_ascii=False))
    for name, box in sorted(layout["elements"].items()):
        lines.append("")
        prefix = "PASSPORT_LAYOUT_" + name.upper() + "_"
        for key in ("x", "y", "width", "height", "font_size", "line_height", "baseline_from_bottom", "letter_spacing", "max_lines", "source_width", "source_height", "pivot_x", "pivot_y"):
            if key in box:
                lines.append("#define " + prefix + key.upper() + " " + str(box[key]))
        if name == "avatar":
            lines.append("#define " + prefix + "SCALE_256 " + str(box["width"] * 256 // box["source_width"]))
        if "c_font" in box:
            lines.append("#define " + prefix + "FONT " + box["c_font"])
        if "color" in box:
            lines.append("#define " + prefix + "COLOR PASSPORT_LAYOUT_COLOR_" + box["color"].upper())
        if "align" in box:
            lines.append("#define " + prefix + "ALIGN LV_TEXT_ALIGN_" + box["align"].upper())
            lines.append("#define " + prefix + "LONG_MODE LV_LABEL_LONG_" + ("DOT" if box.get("overflow") == "ellipsis" else "CLIP"))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated header is stale; never modify files")
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=HEADER)
    args = parser.parse_args()
    try:
        expected = render_header(load_layout(args.source))
    except (OSError, ValueError, KeyError) as error:
        parser.exit(1, "Badge layout invalid: " + str(error) + "\n")
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Badge layout header is stale; run python3 tools/generate_badge_layout.py\n")
        print("Shared badge layout: PASS (JSON and C constants match)")
    else:
        args.output.write_text(expected, encoding="utf-8")
        print("Generated " + str(args.output))


if __name__ == "__main__":
    main()
